name: chatbot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.4
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_ffmpeg: ^0.4.2
  flutter_sound: ^9.2.13
  flutter_tts: ^3.8.5
  fluttertoast: ^8.2.6
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  permission_handler: ^11.0.1
  record: ^5.0.4
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

  # 플러터 런처 아이콘 설정
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/aieev.jpeg" # 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/chatbot.png
    - assets/aieev.jpeg
